import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import PDFDocument from 'pdfkit';
import { prisma } from '../db.js';
import { HttpError } from '../middleware/error.js';
import { requireCapability } from '../middleware/auth.js';
import { bulkPiiExportLimiter } from '../middleware/rateLimit.js';
import { recordCriticalAudit } from '../lib/audit.js';
import { getBlobStore } from '../lib/blobStore.js';
import { COMPANY_INFO, formatRef } from '../lib/emailTemplates.js';
import { ALTO_POLICIES } from '../lib/altoHrContent.js';
import { buildPaystubDataFromItem, paystubItemInclude } from '../lib/paystubData.js';
import { renderPaystubPdf } from '../lib/paystub.js';

/**
 * Client-audit packet generator.
 *
 * Built for the recurring vendor-compliance audits our clients run
 * (Walmart's scope letter is the template): one download assembles the
 * entire response — worker roster, Form I-9s with identity documents,
 * E-Verify confirmations, signed attestation letters for the legal-history
 * items, pay-lawfulness evidence (punches, pay register, paystubs,
 * externally-processed payments), the harassment-reporting process with
 * its acknowledgment log, and the background-check register — as one ZIP
 * whose numbered folders mirror the audit scope, fronted by a letterheaded
 * cover manifest.
 *
 * This is the single largest PII export in the product (I-9 images, SSN
 * cards, pay data for a whole roster in one file), so it takes the same
 * posture as the SSN reveal: view:hr-admin, a written reason, the bulk-PII
 * rate limiter, and a CRITICAL audit row persisted before the first byte
 * streams.
 */

export const auditPacketRouter = Router();

const HR_ADMIN = requireCapability('view:hr-admin');

const GenerateInputSchema = z.object({
  clientId: z.string().uuid(),
  /** Calendar dates, YYYY-MM-DD, inclusive. */
  periodStart: z.string().date(),
  periodEnd: z.string().date(),
  reason: z.string().trim().min(10).max(500),
});

/* ----- small helpers ----------------------------------------------------- */

const csvCell = (v: string | number | null | undefined): string => {
  const s = v === null || v === undefined ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const csv = (rows: Array<Array<string | number | null | undefined>>): string =>
  rows.map((r) => r.map(csvCell).join(',')).join('\r\n') + '\r\n';

const ymd = (d: Date | null | undefined): string =>
  d ? d.toISOString().slice(0, 10) : '';
const iso = (d: Date | null | undefined): string => (d ? d.toISOString() : '');
const money = (v: unknown): string =>
  v === null || v === undefined ? '' : Number(v).toFixed(2);

const safeName = (s: string): string =>
  s.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'unnamed';

/** Letterheaded PDF: title + paragraphs (+ optional signature block). */
function renderLetterPdf(opts: {
  title: string;
  refId: string;
  paragraphs: string[];
  signatureBlock?: boolean;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 64 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Letterhead
    doc.font('Helvetica-Bold').fontSize(18).fillColor('#0F2A44').text(COMPANY_INFO.name);
    doc.font('Helvetica-Oblique').fontSize(8.5).fillColor('#555555').text(COMPANY_INFO.tagline);
    doc
      .font('Helvetica')
      .fontSize(8.5)
      .text(
        `${COMPANY_INFO.address}  ·  ${COMPANY_INFO.phone}  ·  ${COMPANY_INFO.email}  ·  ${COMPANY_INFO.hours}`,
      );
    doc.moveDown(0.5);
    doc
      .moveTo(64, doc.y)
      .lineTo(doc.page.width - 64, doc.y)
      .lineWidth(1)
      .strokeColor('#C9A24C')
      .stroke();
    doc.moveDown(1.2);

    doc.font('Helvetica-Bold').fontSize(13).fillColor('#1A1A1A').text(opts.title);
    doc.moveDown(0.8);
    doc.font('Helvetica').fontSize(10.5).fillColor('#1A1A1A');
    for (const p of opts.paragraphs) {
      doc.text(p, { lineGap: 2.5 });
      doc.moveDown(0.7);
    }

    if (opts.signatureBlock) {
      doc.moveDown(2);
      doc.text('_________________________________', { lineGap: 2 });
      doc.text('Signature');
      doc.moveDown(1);
      doc.text('_________________________________', { lineGap: 2 });
      doc.text('Name and title (printed)');
      doc.moveDown(1);
      doc.text('_________________________________', { lineGap: 2 });
      doc.text('Date');
    }

    doc.moveDown(2);
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#777777')
      .text(`Reference: ${opts.refId} · Generated by the Alto People platform`);
    doc.end();
  });
}

/* ----- the generator ------------------------------------------------------ */

auditPacketRouter.post(
  '/generate',
  HR_ADMIN,
  bulkPiiExportLimiter,
  async (req: Request, res: Response) => {
    const input = GenerateInputSchema.parse(req.body);
    if (input.periodEnd < input.periodStart) {
      throw new HttpError(400, 'invalid_period', 'periodEnd must be on or after periodStart.');
    }
    const start = new Date(`${input.periodStart}T00:00:00Z`);
    const endExcl = new Date(`${input.periodEnd}T00:00:00Z`);
    endExcl.setUTCDate(endExcl.getUTCDate() + 1);

    const client = await prisma.client.findFirst({
      where: { id: input.clientId, deletedAt: null },
      select: { id: true, name: true },
    });
    if (!client) throw new HttpError(404, 'client_not_found', 'Client not found');

    /* Roster: anyone assigned to one of the client's locations during the
     * period, plus anyone with APPROVED worked time attributed to the
     * client in the period. Union, because assignment records and time
     * attribution can each exist without the other. */
    const locations = await prisma.location.findMany({
      where: { clientId: client.id, deletedAt: null },
      select: { id: true, name: true },
    });
    const locationName = new Map(locations.map((l) => [l.id, l.name]));

    const [assignments, workedEntries] = await Promise.all([
      prisma.associateAssignment.findMany({
        where: {
          locationId: { in: locations.map((l) => l.id) },
          startedAt: { lt: endExcl },
          OR: [{ endedAt: null }, { endedAt: { gte: start } }],
        },
        select: { associateId: true, locationId: true, startedAt: true, endedAt: true },
      }),
      prisma.timeEntry.findMany({
        where: {
          clientId: client.id,
          status: 'APPROVED',
          clockInAt: { gte: start, lt: endExcl },
        },
        select: {
          associateId: true,
          clockInAt: true,
          clockOutAt: true,
          status: true,
          locationId: true,
          breaks: { select: { startedAt: true, endedAt: true } },
        },
        orderBy: { clockInAt: 'asc' },
        take: 50_000,
      }),
    ]);

    const rosterIds = [
      ...new Set([
        ...assignments.map((a) => a.associateId),
        ...workedEntries.map((e) => e.associateId),
      ]),
    ];
    if (rosterIds.length === 0) {
      throw new HttpError(
        404,
        'empty_roster',
        'No workers were assigned to (or worked approved time at) this client in the selected period.',
      );
    }

    const associates = await prisma.associate.findMany({
      where: { id: { in: rosterIds }, deletedAt: null },
      select: {
        id: true,
        firstName: true,
        lastName: true,
        email: true,
        employmentType: true,
        i9Verification: {
          select: {
            citizenshipStatus: true,
            section1CompletedAt: true,
            section2CompletedAt: true,
            documentList: true,
            supportingDocIds: true,
            section2Verifier: { select: { email: true } },
            eVerifyCaseNumber: true,
            eVerifyStatus: true,
            eVerifyCaseOpenedAt: true,
            eVerifyClosedAt: true,
          },
        },
        applications: {
          where: { deletedAt: null, clientId: client.id },
          orderBy: { invitedAt: 'desc' },
          take: 1,
          select: { position: true, startDate: true, status: true },
        },
        backgroundChecks: {
          select: { provider: true, status: true, initiatedAt: true, completedAt: true },
          orderBy: { initiatedAt: 'desc' },
        },
      },
      orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }],
    });
    const refId = formatRef();
    const generatedAt = new Date();

    // The audit row lands BEFORE any PII streams — same rule as the SSN
    // reveal: a missing row is the difference between an audited
    // disclosure and silent exfiltration.
    await recordCriticalAudit(
      {
        actorUserId: req.user!.id,
        clientId: client.id,
        action: 'compliance.audit_packet_generated',
        entityType: 'Client',
        entityId: client.id,
        metadata: {
          ip: req.ip ?? null,
          userAgent: req.headers['user-agent'] ?? null,
          reason: input.reason,
          periodStart: input.periodStart,
          periodEnd: input.periodEnd,
          workerCount: associates.length,
          reference: refId,
        },
      },
      'compliance.audit_packet_generated',
    );

    const { default: archiver } = await import('archiver');
    const zipName = `audit-packet-${safeName(client.name)}-${input.periodStart}-to-${input.periodEnd}.zip`;
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${zipName}"`);
    res.setHeader('Cache-Control', 'private, no-store');
    const archive = archiver('zip', { zlib: { level: 6 } });
    archive.on('error', (err: Error) => {
      console.error('[audit-packet] archive error', err);
      res.destroy(err);
    });
    archive.pipe(res);

    const blobStore = getBlobStore();
    const periodLabel = `${input.periodStart} to ${input.periodEnd}`;
    const audience = `${client.name} vendor-compliance audit`;

    /* 01 — Worker roster --------------------------------------------------- */
    const assignmentsByAssociate = new Map<string, typeof assignments>();
    for (const a of assignments) {
      const arr = assignmentsByAssociate.get(a.associateId) ?? [];
      arr.push(a);
      assignmentsByAssociate.set(a.associateId, arr);
    }
    archive.append(
      csv([
        ['Last name', 'First name', 'Email', 'Position', 'Employment type', 'Client start date', 'Site(s)', 'I-9 complete', 'E-Verify case'],
        ...associates.map((a) => {
          const app = a.applications[0];
          const sites = [
            ...new Set(
              (assignmentsByAssociate.get(a.id) ?? []).map(
                (x) => locationName.get(x.locationId) ?? x.locationId,
              ),
            ),
          ].join('; ');
          const i9 = a.i9Verification;
          return [
            a.lastName,
            a.firstName,
            a.email,
            app?.position ?? '',
            a.employmentType,
            ymd(app?.startDate ?? null),
            sites,
            i9?.section1CompletedAt && i9?.section2CompletedAt ? 'Yes' : 'No',
            i9?.eVerifyCaseNumber ?? '',
          ];
        }),
      ]),
      { name: '01-worker-roster/worker-roster.csv' },
    );

    /* 02 — Form I-9s + identity documents ---------------------------------- */
    const i9DocKinds = ['ID', 'SSN_CARD', 'I9_SUPPORTING', 'J1_VISA', 'J1_DS2019'] as const;
    const i9Docs = await prisma.documentRecord.findMany({
      where: {
        associateId: { in: rosterIds },
        deletedAt: null,
        status: { notIn: ['REJECTED', 'EXPIRED'] },
        kind: { in: [...i9DocKinds] },
      },
      select: {
        associateId: true,
        kind: true,
        filename: true,
        s3Key: true,
        i9DocTitle: true,
        i9List: true,
        side: true,
        verifiedAt: true,
      },
    });
    const docsByAssociate = new Map<string, typeof i9Docs>();
    for (const d of i9Docs) {
      const arr = docsByAssociate.get(d.associateId) ?? [];
      arr.push(d);
      docsByAssociate.set(d.associateId, arr);
    }
    let missingBlobs = 0;
    for (const a of associates) {
      const folder = `02-form-i9/${safeName(`${a.lastName}-${a.firstName}`)}-${a.id.slice(0, 4)}`;
      const i9 = a.i9Verification;
      const docs = docsByAssociate.get(a.id) ?? [];
      const summary = [
        `FORM I-9 RECORD — ${a.firstName} ${a.lastName}`,
        `Generated from the Alto People compliance system · ${audience}`,
        '',
        `Citizenship attestation : ${i9?.citizenshipStatus ?? 'NOT ON FILE'}`,
        `Section 1 completed     : ${iso(i9?.section1CompletedAt) || 'NOT ON FILE'}`,
        `Section 2 completed     : ${iso(i9?.section2CompletedAt) || 'NOT ON FILE'}`,
        `Section 2 verifier      : ${i9?.section2Verifier?.email ?? '—'}`,
        `Document list used      : ${i9?.documentList ?? '—'}`,
        '',
        'Identity / eligibility documents on file:',
        ...(docs.length
          ? docs.map(
              (d) =>
                `  - [${d.kind}${d.side ? ` ${d.side}` : ''}] ${d.i9DocTitle ?? d.filename}${d.i9List ? ` (List ${d.i9List})` : ''}${d.verifiedAt ? ` — verified ${ymd(d.verifiedAt)}` : ''}`,
            )
          : ['  (none on file)']),
      ].join('\n');
      archive.append(summary, { name: `${folder}/i9-summary.txt` });
      for (const d of docs) {
        if (!d.s3Key) {
          missingBlobs += 1;
          continue;
        }
        const blob = await blobStore.get(d.s3Key);
        if (!blob) {
          missingBlobs += 1;
          continue;
        }
        archive.append(blob, {
          name: `${folder}/${safeName(`${d.kind}${d.side ? `-${d.side}` : ''}-${d.filename}`)}`,
        });
      }
    }

    /* 03 — E-Verify confirmation ------------------------------------------- */
    archive.append(
      csv([
        ['Last name', 'First name', 'E-Verify case number', 'Status', 'Case opened', 'Case closed'],
        ...associates.map((a) => [
          a.lastName,
          a.firstName,
          a.i9Verification?.eVerifyCaseNumber ?? 'NO CASE ON FILE',
          a.i9Verification?.eVerifyStatus ?? '',
          iso(a.i9Verification?.eVerifyCaseOpenedAt),
          iso(a.i9Verification?.eVerifyClosedAt),
        ]),
      ]),
      { name: '03-e-verify/e-verify-register.csv' },
    );

    /* 04 — Attestation letters (legal-history scope items) ------------------ */
    const attestationIntro = `${COMPANY_INFO.legalName} ("the Company") provides this attestation in connection with the ${audience}, covering the twenty-four (24) months preceding the date of signature below.`;
    const attestationClose =
      'The undersigned is an authorized officer of the Company and affirms, after reasonable inquiry, that the statements above are true and correct as of the date of signature. Supporting documentation, where any exists, is included alongside this letter.';
    const attestations: Array<{ file: string; title: string; body: string }> = [
      {
        file: '04-attestations/attestation-1-immigration-enforcement.pdf',
        title: 'Attestation — Immigration Enforcement History',
        body:
          'The Company has NOT been fined, criminally charged, or convicted of knowingly employing unauthorized workers by U.S. Immigration and Customs Enforcement (ICE), the Department of Justice (DOJ), U.S. Border Patrol, the Department of Labor (DOL), or the Office of Immigrant and Employee Rights (IER) within the past twenty-four (24) months.',
      },
      {
        file: '04-attestations/attestation-2-wage-and-hour.pdf',
        title: 'Attestation — Wage & Hour Compliance History',
        body:
          'The Company has NOT been fined, issued a warning notice, criminally charged with, or convicted of failing to pay at least the minimum wage, failing to pay overtime, or failing to allow workers to take meal and rest breaks as required by law.',
      },
      {
        file: '04-attestations/attestation-3-back-wages.pdf',
        title: 'Attestation — Back Wages',
        body:
          'The Company has NOT paid back wages in connection with any civil or administrative proceeding (whether or not subject to a settlement agreement containing a confidentiality, non-admission-of-liability, or similar clause) due to failure to pay at least the minimum or prevailing wage, applicable overtime rates, or failure to allow workers to take meal and rest breaks as required by law.',
      },
    ];
    for (const att of attestations) {
      archive.append(
        await renderLetterPdf({
          title: att.title,
          refId,
          paragraphs: [
            attestationIntro,
            att.body,
            'IMPORTANT — REVIEW BEFORE SIGNING: this letter is generated as a template stating a clean history. If any covered incident exists, this letter must be corrected and the relevant documentation attached in this folder before the packet is transmitted.',
            attestationClose,
          ],
          signatureBlock: true,
        }),
        { name: att.file },
      );
    }

    /* 05 — Pay-lawfulness records ------------------------------------------ */
    const netMin = (e: (typeof workedEntries)[number]): number => {
      if (!e.clockOutAt) return 0;
      const end = e.clockOutAt.getTime();
      let ms = end - e.clockInAt.getTime();
      for (const b of e.breaks) {
        const bEnd = b.endedAt ? b.endedAt.getTime() : end;
        ms -= Math.max(0, bEnd - b.startedAt.getTime());
      }
      return Math.max(0, Math.round(ms / 60_000));
    };
    const nameById = new Map(associates.map((a) => [a.id, `${a.lastName}, ${a.firstName}`]));
    archive.append(
      csv([
        ['Worker', 'Date', 'Clock in (UTC)', 'Clock out (UTC)', 'Break minutes', 'Net worked minutes', 'Site', 'Status'],
        ...workedEntries.map((e) => [
          nameById.get(e.associateId) ?? e.associateId,
          ymd(e.clockInAt),
          iso(e.clockInAt),
          iso(e.clockOutAt),
          e.clockOutAt
            ? Math.round(
                (e.clockOutAt.getTime() - e.clockInAt.getTime()) / 60_000 - netMin(e),
              )
            : '',
          e.clockOutAt ? netMin(e) : '',
          e.locationId ? locationName.get(e.locationId) ?? '' : '',
          e.status,
        ]),
      ]),
      { name: '05-pay-records/time-punch-records.csv' },
    );

    const payItems = await prisma.payrollItem.findMany({
      where: {
        associateId: { in: rosterIds },
        payrollRun: {
          status: { not: 'CANCELLED' },
          periodStart: { lt: endExcl },
          periodEnd: { gte: start },
        },
      },
      include: paystubItemInclude(),
      orderBy: [{ payrollRun: { periodStart: 'asc' } }, { associate: { lastName: 'asc' } }],
      take: 2_000,
    });
    archive.append(
      csv([
        ['Worker', 'Period start', 'Period end', 'Run status', 'Hours', 'Gross', 'Federal tax', 'FICA', 'Medicare', 'State tax', 'Local tax', 'Net pay', 'Disbursed at'],
        ...payItems.map((it) => [
          `${it.associate.lastName}, ${it.associate.firstName}`,
          ymd(it.payrollRun.periodStart),
          ymd(it.payrollRun.periodEnd),
          it.payrollRun.status,
          money(it.hoursWorked),
          money(it.grossPay),
          money(it.federalWithholding),
          money(it.fica),
          money(it.medicare),
          money(it.stateWithholding),
          money(it.localWithholding),
          money(it.netPay),
          iso(it.payrollRun.disbursedAt),
        ]),
      ]),
      { name: '05-pay-records/pay-register.csv' },
    );

    const PAYSTUB_CAP = 300;
    const disbursed = payItems.filter((it) => it.status === 'DISBURSED');
    let stubCount = 0;
    for (const it of disbursed) {
      if (stubCount >= PAYSTUB_CAP) break;
      try {
        const data = await buildPaystubDataFromItem(prisma, it);
        const pdf = await renderPaystubPdf(data);
        archive.append(pdf, {
          name: `05-pay-records/paystubs/${safeName(`${it.associate.lastName}-${it.associate.firstName}`)}-${ymd(it.payrollRun.periodStart)}.pdf`,
        });
        stubCount += 1;
      } catch (err) {
        console.warn('[audit-packet] paystub render failed for item', it.id, err);
      }
    }

    const externalPayments = await prisma.externalPayment.findMany({
      where: {
        associateId: { in: rosterIds },
        deletedAt: null,
        periodStart: { lt: endExcl },
        periodEnd: { gte: start },
      },
      include: { evidence: { where: { deletedAt: null } } },
      orderBy: { periodEnd: 'asc' },
    });
    if (externalPayments.length > 0) {
      archive.append(
        csv([
          ['Worker', 'Period start', 'Period end', 'Pay date', 'Gross', 'Net', 'Method', 'Reference', 'Evidence files'],
          ...externalPayments.map((p) => [
            nameById.get(p.associateId) ?? p.associateId,
            ymd(p.periodStart),
            ymd(p.periodEnd),
            ymd(p.payDate),
            money(p.grossAmount),
            money(p.netAmount),
            p.method,
            p.reference ?? '',
            p.evidence.map((d) => d.filename).join('; '),
          ]),
        ]),
        { name: '05-pay-records/external-payments/external-payments.csv' },
      );
      for (const p of externalPayments) {
        for (const d of p.evidence) {
          if (!d.s3Key) continue;
          const blob = await blobStore.get(d.s3Key);
          if (!blob) {
            missingBlobs += 1;
            continue;
          }
          archive.append(blob, {
            name: `05-pay-records/external-payments/${safeName(`${nameById.get(p.associateId) ?? p.associateId}`)}-${ymd(p.periodEnd)}-${safeName(d.filename)}`,
          });
        }
      }
    }

    /* 06 — Harassment / discrimination reporting process -------------------- */
    const eeoPolicy = ALTO_POLICIES.find((p) => /anti-harassment/i.test(p.title));
    archive.append(
      [
        'HARASSMENT AND DISCRIMINATION REPORTING PROCESS',
        `${COMPANY_INFO.legalName}`,
        '',
        'Every associate has three always-available reporting channels:',
        '',
        '1. The Alto People concern-reporting tool (in-app HR case system): the',
        '   associate opens a case from their portal; cases are tracked with a',
        '   documented status history and are visible only to HR case managers.',
        '2. Direct report to the HR Administrator — contact information is',
        '   printed in every company email footer and in the associate portal.',
        `3. ${COMPANY_INFO.email} · ${COMPANY_INFO.phone} (${COMPANY_INFO.hours}).`,
        '',
        'The Anti-Harassment policy is incorporated into every associate\'s',
        'employment agreement (Section 17 — Equal Employment Opportunity and',
        'Anti-Harassment) and acknowledged at onboarding; the acknowledgment',
        'log for the audited roster is included alongside this document.',
      ].join('\n'),
      { name: '06-harassment-reporting/reporting-process.txt' },
    );
    if (eeoPolicy) {
      archive.append(`${eeoPolicy.title} (v${eeoPolicy.version})\n\n${eeoPolicy.body}`, {
        name: `06-harassment-reporting/${safeName(eeoPolicy.title)}.txt`,
      });
    }
    const acks = await prisma.policyAcknowledgment.findMany({
      where: { associateId: { in: rosterIds } },
      select: {
        associateId: true,
        acknowledgedAt: true,
        policy: { select: { title: true } },
      },
      orderBy: { acknowledgedAt: 'asc' },
    });
    archive.append(
      csv([
        ['Worker', 'Policy', 'Acknowledged at'],
        ...acks.map((k) => [
          nameById.get(k.associateId) ?? k.associateId,
          k.policy.title,
          iso(k.acknowledgedAt),
        ]),
      ]),
      { name: '06-harassment-reporting/policy-acknowledgment-log.csv' },
    );

    /* 07 — Background checks ------------------------------------------------ */
    archive.append(
      csv([
        ['Worker', 'Provider', 'Status', 'Initiated', 'Completed'],
        ...associates.flatMap((a) =>
          a.backgroundChecks.length
            ? a.backgroundChecks.map((b) => [
                `${a.lastName}, ${a.firstName}`,
                b.provider,
                b.status,
                iso(b.initiatedAt),
                iso(b.completedAt),
              ])
            : [[`${a.lastName}, ${a.firstName}`, 'NO CHECK ON FILE', '', '', '']],
        ),
      ]),
      { name: '07-background-checks/background-check-register.csv' },
    );
    const bgDocs = await prisma.documentRecord.findMany({
      where: {
        associateId: { in: rosterIds },
        deletedAt: null,
        kind: 'BACKGROUND_CHECK_RESULT',
        status: { notIn: ['REJECTED', 'EXPIRED'] },
      },
      select: { associateId: true, filename: true, s3Key: true },
    });
    for (const d of bgDocs) {
      if (!d.s3Key) continue;
      const blob = await blobStore.get(d.s3Key);
      if (!blob) {
        missingBlobs += 1;
        continue;
      }
      archive.append(blob, {
        name: `07-background-checks/results/${safeName(`${nameById.get(d.associateId) ?? d.associateId}`)}-${safeName(d.filename)}`,
      });
    }

    /* 08 — Subcontractors ---------------------------------------------------- */
    archive.append(
      await renderLetterPdf({
        title: 'Subcontractor Statement',
        refId,
        paragraphs: [
          attestationIntro,
          `The workers listed in this packet are direct associates of the Company. The Company does not engage subcontractors to provide services on ${client.name} properties. Should any subcontractor be engaged in the future, the Company will obtain and provide the subcontractor's worker roster, Form I-9 records with supporting eligibility and identity documentation, and E-Verify confirmations, as required by the audit scope.`,
          'IMPORTANT — REVIEW BEFORE SIGNING: if subcontractors ARE currently engaged, replace this statement with the subcontractor documentation described above.',
          attestationClose,
        ],
        signatureBlock: true,
      }),
      { name: '08-subcontractors/subcontractor-statement.pdf' },
    );

    /* 00 — Cover manifest (added last so the counts are real) ---------------- */
    archive.append(
      await renderLetterPdf({
        title: `Audit Response Packet — ${client.name}`,
        refId,
        paragraphs: [
          `Prepared by ${COMPANY_INFO.legalName} in response to the ${audience}. Audit period: ${periodLabel}. Generated ${generatedAt.toISOString()} by ${req.user!.email} via the Alto People compliance platform.`,
          `Contents (folders numbered to match the audit scope):`,
          `01 — Worker roster: ${associates.length} workers providing services on ${client.name} properties during the period.`,
          `02 — Form I-9 records and identity/eligibility documents: one folder per worker (${i9Docs.length} documents).`,
          `03 — E-Verify register: case number, status, and dates per worker.`,
          `04 — Attestation letters (immigration enforcement, wage & hour, back wages): REQUIRE OFFICER REVIEW AND SIGNATURE before transmission.`,
          `05 — Pay records: ${workedEntries.length} approved time entries, ${payItems.length} pay-register lines, ${stubCount} paystub PDFs${disbursed.length > PAYSTUB_CAP ? ` (of ${disbursed.length} — capped; regenerate with a narrower period for the remainder)` : ''}${externalPayments.length ? `, ${externalPayments.length} externally-processed payment records with evidence` : ''}.`,
          `06 — Harassment/discrimination reporting process, policy text, and acknowledgment log (${acks.length} acknowledgments).`,
          `07 — Background checks: register plus ${bgDocs.length} result documents.`,
          `08 — Subcontractor statement: REQUIRES OFFICER REVIEW AND SIGNATURE.`,
          missingBlobs > 0
            ? `NOTE: ${missingBlobs} document file(s) referenced by records could not be retrieved from storage and are absent; their records still appear in the registers.`
            : 'All referenced document files were retrieved successfully.',
          `This packet contains confidential personnel information. Handle and transmit according to the data-handling terms of the applicable MSA. ${COMPANY_INFO.name} · ${COMPANY_INFO.address} · ${COMPANY_INFO.phone} · ${COMPANY_INFO.email}`,
        ],
      }),
      { name: '00-cover/manifest.pdf' },
    );

    await archive.finalize();
  },
);
