import ExcelJS from 'exceljs';
import type { TimesheetWeekResponse } from '@alto-people/shared';

/**
 * Fieldglass-shaped weekly timesheet as an .xlsx the buyer's list view
 * mirrors 1:1: Status · ID · Revision · Worker · Site · End · ST · OT · DT ·
 * Others · NB · Total. One row per worker per week (Sat→Fri), the week-ending
 * Friday in "End", net approved hours in "Others". ID is blank (Fieldglass
 * generates it) and Revision is 0 — kept so the columns line up for copy/paste.
 */

const BAND = 'FF1F2A37';
const SUBTOTAL = 'FFEAEDF1';
const MUTED = 'FF6B7280';
const INK = 'FF111827';
const WARN = 'FFB5360F';
const HOURS_FMT = '0.00';

const THIN: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: 'FFD1D5DB' } },
  left: { style: 'thin', color: { argb: 'FFD1D5DB' } },
  bottom: { style: 'thin', color: { argb: 'FFD1D5DB' } },
  right: { style: 'thin', color: { argb: 'FFD1D5DB' } },
};

const HOUR_COLS = [7, 8, 9, 10, 11, 12]; // ST, OT, DT, Others, NB, Total

export async function renderTimesheetXlsx(
  data: TimesheetWeekResponse,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Alto People';
  wb.created = new Date(data.generatedAt);

  const ws = wb.addWorksheet('Timesheets', {
    pageSetup: {
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      margins: { left: 0.4, right: 0.4, top: 0.6, bottom: 0.6, header: 0.3, footer: 0.3 },
    },
    headerFooter: {
      oddFooter: '&LConfidential · Generated by Alto People&RPage &P of &N',
    },
  });

  ws.columns = [
    { key: 'status', width: 16 },
    { key: 'id', width: 16 },
    { key: 'rev', width: 9 },
    { key: 'worker', width: 26 },
    { key: 'site', width: 26 },
    { key: 'end', width: 13 },
    { key: 'st', width: 9 },
    { key: 'ot', width: 9 },
    { key: 'dt', width: 9 },
    { key: 'others', width: 11 },
    { key: 'nb', width: 9 },
    { key: 'total', width: 11 },
  ];

  // Letterhead
  ws.mergeCells('A1:L1');
  const title = ws.getCell('A1');
  title.value = 'Fieldglass Timesheets';
  title.font = { bold: true, size: 18, color: { argb: INK } };
  ws.getRow(1).height = 24;

  ws.mergeCells('A2:L2');
  ws.getCell('A2').value = 'ALTO PEOPLE';
  ws.getCell('A2').font = { bold: true, size: 9, color: { argb: MUTED } };

  const meta: Array<[string, string]> = [
    ['Week', `Sat ${data.weekStart} → Fri ${data.weekEndIso}`],
    ['Week ending', data.weekEnding],
    ['Basis', 'Approved hours only · net of unpaid breaks'],
    ['Generated', new Date(data.generatedAt).toLocaleString('en-US')],
  ];
  let r = 4;
  for (const [label, value] of meta) {
    ws.getCell(`A${r}`).value = label.toUpperCase();
    ws.getCell(`A${r}`).font = { size: 8, color: { argb: MUTED } };
    ws.mergeCells(`B${r}:L${r}`);
    ws.getCell(`B${r}`).value = value;
    ws.getCell(`B${r}`).font = { bold: true, size: 10, color: { argb: INK } };
    r += 1;
  }
  if (data.pendingCount > 0) {
    ws.mergeCells(`A${r}:L${r}`);
    const warn = ws.getCell(`A${r}`);
    warn.value = `PROVISIONAL — ${data.pendingCount} entr${data.pendingCount === 1 ? 'y is' : 'ies are'} still pending approval and are NOT included in these totals.`;
    warn.font = { bold: true, size: 9, color: { argb: WARN } };
    r += 1;
  }
  r += 1; // spacer

  const headerRowNum = r;
  const header = ws.getRow(headerRowNum);
  header.values = [
    'Status',
    'ID',
    'Revision',
    'Worker',
    'Site',
    'End',
    'ST',
    'OT',
    'DT',
    'Others',
    'NB',
    'Total',
  ];
  header.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
  header.height = 18;
  header.eachCell((cell) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BAND } };
    cell.alignment = { vertical: 'middle', wrapText: true };
    cell.border = THIN;
  });

  r += 1;
  const firstDataRow = r;
  for (const row of data.rows) {
    const xl = ws.getRow(r);
    xl.values = [
      row.status === 'PENDING' ? 'Pending Approval' : 'Ready',
      '', // ID — Fieldglass-generated
      0, // Revision
      row.worker,
      row.site,
      data.weekEnding,
      row.st,
      row.ot,
      row.dt,
      row.others,
      row.nb,
      row.total,
    ];
    xl.eachCell((cell, col) => {
      cell.border = THIN;
      if (HOUR_COLS.includes(col)) {
        cell.numFmt = HOURS_FMT;
        cell.alignment = { horizontal: 'right' };
      }
    });
    if ((r - headerRowNum) % 2 === 0) {
      xl.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4F6F8' } };
      });
    }
    r += 1;
  }
  const lastDataRow = r - 1;

  // TOTAL row
  const totalRow = ws.getRow(r);
  totalRow.values = [
    'TOTAL',
    '',
    '',
    `${data.rows.length} worker${data.rows.length === 1 ? '' : 's'}`,
    '',
    '',
    0,
    0,
    0,
    data.totalHours,
    0,
    data.totalHours,
  ];
  totalRow.font = { bold: true, color: { argb: INK } };
  totalRow.eachCell((cell, col) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: SUBTOTAL } };
    cell.border = { ...THIN, top: { style: 'medium', color: { argb: BAND } } };
    if (HOUR_COLS.includes(col)) {
      cell.numFmt = HOURS_FMT;
      cell.alignment = { horizontal: 'right' };
    }
  });
  r += 2;

  const note = ws.getCell(`A${r}`);
  ws.mergeCells(`A${r}:L${r}`);
  note.value =
    'Worker = "Last, First". End = week-ending Friday (week runs Saturday→Friday). Hours are net of unpaid breaks, approved entries only, billed flat under "Others" per the SOW (no ST/OT/DT split). ID is assigned by Fieldglass on entry.';
  note.font = { italic: true, size: 8, color: { argb: MUTED } };
  note.alignment = { wrapText: true };
  ws.getRow(r).height = 28;

  ws.views = [{ state: 'frozen', ySplit: headerRowNum }];
  if (lastDataRow >= firstDataRow) {
    ws.autoFilter = {
      from: { row: headerRowNum, column: 1 },
      to: { row: lastDataRow, column: 12 },
    };
  }
  ws.pageSetup.printTitlesRow = `${headerRowNum}:${headerRowNum}`;

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

export function timesheetFilename(weekEndIso: string): string {
  return `fieldglass-timesheets-week-ending-${weekEndIso}.xlsx`;
}
